pipeline:
  name: Vagrant CI
  identifier: Vagrant_CI
  projectIdentifier: Femi_Sandbox
  orgIdentifier: sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: vagrantfork
        build: <+input>
  stages:
    - stage:
        name: TI
        identifier: TI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: Install_dependencies
                  spec:
                    shell: Sh
                    command: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib gspread
              - step:
                  type: Action
                  name: Setup Ruby
                  identifier: setup_ruby
                  spec:
                    uses: ruby/setup-ruby@v1.152.0
                    with:
                      ruby-version: 3.2.2
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt update
                      sudo apt -y install libarchive-tools
              - step:
                  type: Test
                  name: Test_1
                  identifier: Test_1
                  spec:
                    shell: Sh
                    command: |-
                      set -x
                      bundle exec rake test:unit
                    intelligenceMode: true
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Ignore
